CREATE TABLE IF NOT EXISTS ALUNO (
    ID CHAR(36) NOT NULL PRIMARY KEY,
    USUARIO_FK CHAR(36) NOT NULL,
    CURSO_FK CHAR(36) NOT NULL,
    CRIACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ATUALIZACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);