CREATE TABLE IF NOT EXISTS QUESTAO_DIA (
  QUESTAO_FK CHAR(36) NOT NULL,
  ALUNO_FK CHAR(36) NOT NULL,
  CRIACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ATUALIZACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (QUESTAO_FK, ALUNO_FK)
 );
 
