CREATE TABLE IF NOT EXISTS USUARIO (
  ID CHAR(36) NOT NULL PRIMARY KEY,
  NOME VARCHAR(32) NOT NULL,
  EMAIL VARCHAR(32) NOT NULL,
  SENHA VARCHAR(32) NOT NULL,
  CRIACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ATUALIZACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
 );
