ALTER TABLE ATIVIDADE_AVALIATIVA
  ADD CONSTRAINT ATIVIDADE_AVALIATIVA_TURMA_FK FOREIGN KEY (TURMA_FK) REFERENCES TURMA(ID);

ALTER TABLE AVALIACAO360
  ADD CONSTRAINT AVALIACAO360_GRUPO_FK FOREIGN KEY (GRUPO_FK) REFERENCES GRUPO(ID);

ALTER TABLE AVALIACAO360
  ADD CONSTRAINT AVALIACAO360_ATIVIDADE_AVALIATIVA_FK FOREIGN KEY (ATIVIDADE_AVALIATIVA_FK) REFERENCES ATIVIDADE_AVALIATIVA(ID);

ALTER TABLE AVALIACAO360
  ADD CONSTRAINT AVALIACAO360_ALUNO_FK FOREIGN KEY (ALUNO_FK) REFERENCES ALUNO(ID);

ALTER TABLE GRUPO
  ADD CONSTRAINT GRUPO_TURMA_FK FOREIGN KEY (TURMA_FK) REFERENCES TURMA(ID);

ALTER TABLE GRUPO
  ADD CONSTRAINT GRUPO_ATIVIDADE_AVALIATIVA_FK FOREIGN KEY (ATIVIDADE_AVALIATIVA_FK) REFERENCES ATIVIDADE_AVALIATIVA(ID);

ALTER TABLE TAREFA
  ADD CONSTRAINT TAREFA_GRUPO_FK FOREIGN KEY (GRUPO_FK) REFERENCES GRUPO(ID);

ALTER TABLE TAREFA
  ADD CONSTRAINT TAREFA_ALUNO_FK FOREIGN KEY (ALUNO_FK) REFERENCES ALUNO(ID);

ALTER TABLE QUESTAO_DIA
  ADD CONSTRAINT QUESTAO_DIA_ALUNO_FK FOREIGN KEY (ALUNO_FK) REFERENCES ALUNO(ID);

ALTER TABLE QUESTAO_DIA
  ADD CONSTRAINT QUESTAO_DIA_QUESTAO_FK FOREIGN KEY (QUESTAO_FK) REFERENCES QUESTAO(ID);

ALTER TABLE QUESTAO
  ADD CONSTRAINT QUESTAO_HARDSKILL_FK FOREIGN KEY (HARDSKILL_FK) REFERENCES HARDSKILL(ID);

ALTER TABLE QUESTAO
  ADD CONSTRAINT QUESTAO_USUARIO_FK FOREIGN KEY (USUARIO_FK) REFERENCES USUARIO(ID);

ALTER TABLE ALUNO
  ADD CONSTRAINT ALUNO_CURSO_FK FOREIGN KEY (CURSO_FK) REFERENCES CURSO(ID);

ALTER TABLE ALUNO
  ADD CONSTRAINT ALUNO_USUARIO_FK FOREIGN KEY (USUARIO_FK) REFERENCES USUARIO(ID);

ALTER TABLE PROFESSOR
  ADD CONSTRAINT PROFESSOR_USUARIO_FK FOREIGN KEY (USUARIO_FK) REFERENCES USUARIO(ID);

ALTER TABLE TURMA
  ADD CONSTRAINT TURMA_DISCIPLINA_FK FOREIGN KEY (DISCIPLINA_FK) REFERENCES DISCIPLINA(ID);
