ALTER TABLE JT_ALUNO_HARDSKILL
    ADD CONSTRAINT JT_ALUNO_HARDSKILL_ALUNO_FK FOREIGN KEY (ALUNO_FK) REFERENCES ALUNO(ID);

ALTER TABLE JT_ALUNO_HARDSKILL
    ADD CONSTRAINT JT_ALUNO_HARDSKILL_HARDSKILL_FK FOREIGN KEY (HARDSKILL_FK) REFERENCES HARDSKILL(ID);

ALTER TABLE JT_ALUNO_TURMA
    ADD CONSTRAINT JT_ALUNO_TURMA_ALUNO_FK FOREIGN KEY (ALUNO_FK) REFERENCES ALUNO(ID);

ALTER TABLE JT_ALUNO_TURMA
    ADD CONSTRAINT JT_ALUNO_TURMA_TURMA_FK FOREIGN KEY (TURMA_FK) REFERENCES TURMA(ID);

ALTER TABLE JT_ATIVIDADE_AVALIATIVA_HARDSKILL
    ADD CONSTRAINT JT_ATIVIDADE_AVALIATIVA_HARDSKILL_ATIVIDADE_AVALIATIVA_FK FOREIGN KEY (ATIVIDADE_AVALIATIVA_FK) REFERENCES ATIVIDADE_AVALIATIVA(ID);

ALTER TABLE JT_ATIVIDADE_AVALIATIVA_HARDSKILL
    ADD CONSTRAINT JT_ATIVIDADE_AVALIATIVA_HARDSKILL_HARDSKILL_FK FOREIGN KEY (HARDSKILL_FK) REFERENCES HARDSKILL(ID);

ALTER TABLE JT_AVALIACAO360_SOFTSKILL
    ADD CONSTRAINT JT_AVALIACAO360_SOFTSKILL_SOFTSKILL_FK FOREIGN KEY (SOFTSKILL_FK) REFERENCES SOFTSKILL(ID);

ALTER TABLE JT_AVALIACAO360_SOFTSKILL
    ADD CONSTRAINT JT_AVALIACAO360_SOFTSKILL_AVALIACAO360_FK FOREIGN KEY (AVALIACAO360_FK) REFERENCES AVALIACAO360(ID);

ALTER TABLE JT_CURSO_TURMA
    ADD CONSTRAINT JT_CURSO_TURMA_TURMA_FK FOREIGN KEY (TURMA_FK) REFERENCES TURMA(ID);

ALTER TABLE JT_CURSO_TURMA
    ADD CONSTRAINT JT_CURSO_TURMA_CURSO_FK FOREIGN KEY (CURSO_FK) REFERENCES CURSO(ID);

ALTER TABLE JT_DISCIPLINA_HARDSKILL
    ADD CONSTRAINT JT_DISCIPLINA_HARDSKILL_HARDSKILL_FK FOREIGN KEY (HARDSKILL_FK) REFERENCES HARDSKILL(ID);

ALTER TABLE JT_DISCIPLINA_HARDSKILL
    ADD CONSTRAINT JT_DISCIPLINA_HARDSKILL_DISCIPLINA_FK FOREIGN KEY (DISCIPLINA_FK) REFERENCES DISCIPLINA(ID);

ALTER TABLE JT_DISCIPLINA_PROFESSOR
    ADD CONSTRAINT JT_DISCIPLINA_PROFESSOR_DISCIPLINA_FK FOREIGN KEY (DISCIPLINA_FK) REFERENCES DISCIPLINA(ID);

ALTER TABLE JT_DISCIPLINA_PROFESSOR
    ADD CONSTRAINT JT_DISCIPLINA_PROFESSOR_PROFESSOR_FK FOREIGN KEY (PROFESSOR_FK) REFERENCES PROFESSOR(ID);

ALTER TABLE JT_GRUPO_ALUNO
    ADD CONSTRAINT JT_GRUPO_ALUNO_GRUPO_FK FOREIGN KEY (GRUPO_FK) REFERENCES GRUPO(ID);

ALTER TABLE JT_GRUPO_ALUNO
    ADD CONSTRAINT JT_GRUPO_ALUNO_ALUNO_FK FOREIGN KEY (ALUNO_FK) REFERENCES ALUNO(ID);

ALTER TABLE JT_SOFTSKILL_ALUNO
    ADD CONSTRAINT JT_SOFTSKILL_ALUNO_SOFTSKILL_FK FOREIGN KEY (SOFTSKILL_FK) REFERENCES SOFTSKILL(ID);

ALTER TABLE JT_SOFTSKILL_ALUNO
    ADD CONSTRAINT JT_SOFTSKILL_ALUNO_ALUNO_FK FOREIGN KEY (ALUNO_FK) REFERENCES ALUNO(ID);

ALTER TABLE JT_TURMA_HARDSKILL
    ADD CONSTRAINT JT_TURMA_HARDSKILL_TURMA_FK FOREIGN KEY (TURMA_FK) REFERENCES TURMA(ID);

ALTER TABLE JT_TURMA_HARDSKILL
    ADD CONSTRAINT JT_TURMA_HARDSKILL_HARDSKILL_FK FOREIGN KEY (HARDSKILL_FK) REFERENCES HARDSKILL(ID);

ALTER TABLE JT_TURMA_PROFESSOR
    ADD CONSTRAINT JT_TURMA_PROFESSOR_PROFESSOR_FK FOREIGN KEY (PROFESSOR_FK) REFERENCES PROFESSOR(ID);

ALTER TABLE JT_TURMA_PROFESSOR
    ADD CONSTRAINT JT_TURMA_PROFESSOR_TURMA_FK FOREIGN KEY (TURMA_FK) REFERENCES TURMA(ID);
