CREATE TABLE IF NOT EXISTS AVALIACAO360 (
  ID CHAR(36) NOT NULL,
  NOME VARCHAR(32) NOT NULL,                                             
  DESCRICAO VARCHAR(256),                                                
  GRUPO_FK CHAR(36) NOT NULL,
  ATIVIDADE_AVALIATIVA_FK CHAR(36) NOT NULL,
  ALUNO_FK CHAR(36) NOT NULL,
  CRIACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ATUALIZACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
 );
 
