ALTER TABLE ATIVIDADE_AVALIATIVA
  ADD CONSTRAINT TURMA_FK FOREIGN KEY (TURMA_FK) REFERENCES TURMA(ID);

ALTER TABLE AVALIACAO360
  ADD CONSTRAINT GRUPO_FK FOREIGN KEY (GRUPO_FK) REFERENCES GRUPO(ID);

ALTER TABLE AVALIACAO360
  ADD CONSTRAINT ATIVIDADE_AVALIATIVA_FK FOREIGN KEY (ATIVIDADE_AVALIATIVA_FK) REFERENCES ATIVIDADE_AVALIATIVA(ID);

ALTER TABLE AVALIACAO360
  ADD CONSTRAINT ALUNO_FK FOREIGN KEY (ALUNO_FK) REFERENCES ALUNO(ID);