CREATE TABLE IF NOT EXISTS QUESTAO_DIA (
  QUESTAO_FK CHAR(36) NOT NULL PRIMARY KEY,
  CRIACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ATUALIZACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
 );
 
