CREATE TABLE IF NOT EXISTS QUESTAO (
  ID CHAR(36) NOT NULL PRIMARY KEY,
  ENUNCIADO VARCHAR(512) NOT NULL,
  RESPOSTA_A VARCHAR(32) NOT NULL,
  RESPOSTA_B VARCHAR(32) NOT NULL,
  RESPOSTA_C VARCHAR(32) NOT NULL,
  RESPOSTA_D VARCHAR(32) NOT NULL,
  GABARITO VARCHAR(32) NOT NULL,
  USUARIO_FK CHAR(36) NOT NULL,
  HARDSKILL_FK CHAR(36) NOT NULL,
  CRIACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ATUALIZACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
 );
 
