CREATE TABLE IF NOT EXISTS TAREFA (
  ID CHAR(36) NOT NULL,
  NOME VARCHAR(32) NOT NULL,
  DESCRICAO VARCHAR(256),
  ALUNO_FK CHAR(36) NOT NULL,
  CRIACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ATUALIZACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
 );
 
