CREATE TABLE IF NOT EXISTS USUARIO (
  ID CHAR(36) NOT NULL,
  NOME VARCHAR(32) NOT NULL,
  EMAIL VARCHAR(32) NOT NULL,
  SENHA VARCHAR(32) NOT NULL,
  TIPO CHAR(1) NOT NULL,
  CURSO_FK CHAR(36) NOT NULL,
  CRIACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ATUALIZACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
 );
